Suspension Management project
oracle-samples/ofs-sample-plugins pull request #4
Opened 2023-11-03 19:59 UTC by miquelgall

2023-11-04 00:12 UTC, btoron requested changes

2023-11-04 00:12 UTC, btoron commented on samples/003-SuspensionMng/README.md
> +# getUsers
Change name to SuspensionMgr

2023-11-04 00:12 UTC, btoron commented on samples/003-SuspensionMng/README.md
> +None
Can you please double check this? I thought the values were using some custom properties

2023-11-04 00:12 UTC, btoron commented on samples/003-SuspensionMng/assets/js/utils/jsonview.ts
> +
Check if this file is needed

2023-11-04 00:12 UTC, btoron commented on samples/003-SuspensionMng/assets/css/jsonviewer.scss
Check if this file is needed

2023-11-04 00:12 UTC, btoron commented on samples/.DS_Store
Remove

2023-11-04 00:12 UTC, btoron commented on samples/003-SuspensionMng/plugin.xml
Remove

2023-11-04 00:12 UTC, btoron commented on samples/003-SuspensionMng/README.md
> +None
According to the descriptor:
           "appt_number",
           "length",
           "ETA",
           "astatus",
           "aid",
           "date",
           "A_TOTAL_DURATION",
           "A_TOTAL_DURATION_COMPLETE",
           "A_ORIGINAL_START_TIME",
           "A_ORIGINAL_START_TIME_TZ",
           "A_TOTAL_TIME_TO_SOLVE"

2023-11-15 15:05 UTC, miquelgall reviewed
Changes applied according to recommendations

2023-11-15 15:06 UTC, miquelgall commented on samples/003-SuspensionMng/assets/js/utils/jsonview.ts
> +
File removed

2023-11-15 15:40 UTC, btoron approved these changes

2023-11-15 15:45 UTC, merged